### ISSUE TITLE
chat to a live tab of ChatGPT?

### ISSUE THREAD

**Issue by IlIIIIIIlI** [HenokT/PageChat#1]
if that is possible to sent prompt to a live tab of ChatGPT(https://chat.openai.com/) in the chrome broswer?
I saw an interesting repo about asking to a live tab: https://github.com/countalabs/gpt-chrome/blob/main/background.js but i don't know much about plugin development.

**Comment by HenokT** [comment]
Yeah that's possible but the extension may break if open AI decides to redesign the ChatGPT site. My plan for this extension is to stick with the OpenAI API to interact with GPT and possibly add support for other LLM providers.
